/**
 * Versioned, bounded codes that may cross the internal error boundary.
 * Raw exception messages and upstream response bodies are never safe codes.
 */
export const SAFE_ERROR_TAXONOMY_VERSION = 1 as const;

export const SAFE_ERROR_CODES = Object.freeze([
  "ACCOUNT_DENIED",
  "AGENT_DENIED",
  "ALERT_OUTBOX_UNAVAILABLE",
  "AUDIT_ACCESS_DENIED",
  "AUDIT_APPEND_FAILED",
  "AUDIT_EVENT_INVALID",
  "AUDIT_REQUIRED",
  "CATALOG_INVALID",
  "CHANNEL_BINDING_INVALID",
  "CHANNEL_DENIED",
  "CONFIG_INVALID",
  "CREATE_DISABLED",
  "CREATE_GATE_INVALID",
  "DESTINATION_DENIED",
  "DRAFT_INVALID",
  "INTERNAL_ERROR",
  "JIRA_AUTH_FAILED",
  "JIRA_RATE_LIMITED",
  "JIRA_REQUEST_FAILED",
  "JIRA_SCOPE_INVALID",
  "JIRA_UNKNOWN_RESULT",
  "METRIC_LABEL_INVALID",
  "MIGRATION_APPLY_FAILED",
  "MIGRATION_FUTURE_SCHEMA",
  "MIGRATION_HISTORY_MISMATCH",
  "MIGRATION_NAME_INVALID",
  "MIGRATION_PARTIAL_STATE",
  "MIGRATION_REGISTRY_INVALID",
  "MIGRATION_VERSION_INVALID",
  "MODEL_REQUEST_FAILED",
  "PAYLOAD_INVALID",
  "PAYLOAD_TOO_LARGE",
  "RATE_LIMITED",
  "REPOSITORY_SQL_DENIED",
  "SECRET_REF_MISSING",
  "SENDER_MISSING",
  "STATE_DIR_INVALID",
  "STORAGE_APPLICATION_ID_INVALID",
  "STORAGE_BUSY_TIMEOUT_INVALID",
  "STORAGE_CLOSED",
  "STORAGE_CONNECTION_POLICY_INVALID",
  "STORAGE_CONSISTENCY_FAILED",
  "STORAGE_DURABILITY_INVALID",
  "STORAGE_FILE_EXISTS",
  "STORAGE_FOREIGN_KEY_CHECK_FAILED",
  "STORAGE_NOT_READY",
  "STORAGE_PATH_INVALID",
  "STORAGE_PERMISSION_INVALID",
  "STORAGE_SCHEMA_VERSION_INVALID",
  "STORAGE_STARTUP_FAILED",
  "STORAGE_UPGRADE_BACKUP_INVALID",
  "STORAGE_UPGRADE_BACKUP_REQUIRED",
  "STT_REQUEST_FAILED",
  "TELEGRAM_REQUEST_FAILED",
  "THREAD_DENIED",
  "TOOL_ALLOWLIST_INVALID",
  "TRANSACTION_CALLBACK_MUST_BE_SYNCHRONOUS",
  "TRIGGER_DENIED",
] as const);

export type SafeErrorCode = (typeof SAFE_ERROR_CODES)[number];

const SAFE_ERROR_CODE_SET: ReadonlySet<string> = new Set(SAFE_ERROR_CODES);

export function isSafeErrorCode(value: unknown): value is SafeErrorCode {
  return typeof value === "string" && SAFE_ERROR_CODE_SET.has(value);
}
